# docker-stack.yml
version: "3.8"

services:
  frontend:
    image: ${REGISTRY}/${PROJECT}/${IMAGE}:${TAG}
    ports:
      - "9005:80"
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
